### ISSUE TITLE
Error when typing enter

### ISSUE THREAD

**Issue by gaijin03** [gavinhoward/vim-spacealign#1]
I get this error message when dropping "message" down by typing enter when the cursor is on the first "

```
>------->------->------->-------if.(something).{
>------->------->------->------->-------if.(!xstrcmp(node_ptr->reason,."message"))
>------->------->------->------->------->-------do_someting();
>------->------->------->------->-------}
>------->------->------->-------}
```

![image](https://user-images.githubusercontent.com/3599934/77589295-0592e080-6eb1-11ea-9e52-91a55256e74e.png)

```
root@be39649325ca:~# cat .vimrc 
set noet sts=0 sw=8 ts=8
set cindent
set cinoptions=(0,u0,U0

set list listchars=tab:>-,trail:~,space:.
```

**Comment by gavinhoward** [comment]
The function that is missing is in an `autoload` directory, so it must not be loaded somehow. What plugin manager are you using?

**Comment by gaijin03** [comment]
My bad. In this test case, I'm not using a plugin manager. I only copied vim-spacealign.vim into the vim plugin directory. I copied spacealign.vim into the directory as well and it doesn't error anymore.

However, hitting enter gives more spaces than are needed.
```
{
>------->------->------->-------if.(something).{
>------->------->------->------->-------if.(!xstrcmp(node_ptr->reason,
>------->-------....................................."message"))
>------->------->------->------->------->-------do_someting();
>------->------->------->------->-------}
>------->------->------->-------}
}
```

**Comment by gavinhoward** [comment]
I have found the problem.

The code as written assumes that the file is indented correctly, but as you have shown, that may not be the case.

As you know, `vim` has a reindent command, `=`, which I could use to run on the lines targeted by the plugin before the plugin does anything. Would that be what you would expect or not?

**Comment by gavinhoward** [comment]
Closing.
