### ISSUE TITLE
Bad argument alignment when declaring functions

### ISSUE THREAD

**Issue by asanchez1987** [gavinhoward/vim-spacealign#2]
![bad_alignment](https://user-images.githubusercontent.com/8619167/77659034-d6937200-6f77-11ea-94a7-88078a1d08cb.png)

**Comment by gavinhoward** [comment]
Can you send me your `.vimrc` (or `.config/nvim/init.vim` if you are using Neovim)?

**Comment by asanchez1987** [comment]
Just had

`set listchars=tab:>-
set list
syntax enable
execute pathogen#infect()`

and your repository files in `~/.vim/bundle`

**Comment by gavinhoward** [comment]
I have found the problem.

My plugin tries to follow the user's `cindent` and `cinoptions` as much as possible. This means that it assumes that you have set those two options to what you want.

By default, `vim`'s `cinoptions indents `2 * shiftwidth` for an unclosed parenthesis. To get the behavior you want, you need to add `(0` to `cinoptions`, like so:

```
cinoptions=(0
```

This tells `vim` that you want the arguments aligned to the column after the open parenthesis.

**Comment by gavinhoward** [comment]
Closing.
